AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS MySQL Instance"

Parameters:
  DBName:
    Type: String
  DBUser:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id
  VPCId:
    Type: AWS::EC2::VPC::Id

Resources:
  DBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPCId
      GroupDescription: "MySQL Security Group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "DB Subnets"
      SubnetIds:
        - !Ref SubnetA
        - !Ref SubnetB

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      DBName: !Ref DBName
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      InstanceClass: db.t3.micro
      PubliclyAccessible: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSG
      SkipFinalSnapshot: true

Outputs:
  RDSEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
